# Generated by Django 4.0.5 on 2022-07-02 20:09

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUUIDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefABCDEF123456', length=6, max_length=6, prefix='')),
            ],
        ),
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(max_length=8),
        ),
    ]
