# Generated by Django 4.0.5 on 2022-07-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shortuuidmodel_alter_url_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='UniformResourceLocator',
        ),
    ]
