# Generated by Django 4.0.5 on 2022-07-05 15:44

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_rename_url_uniformresourcelocator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniformresourcelocator',
            old_name='updated_at',
            new_name='edited_at',
        ),
        migrations.RemoveField(
            model_name='uniformresourcelocator',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='uniformresourcelocator',
            name='uuid',
        ),
        migrations.AddField(
            model_name='uniformresourcelocator',
            name='alias',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefABCDEF123456', length=6, max_length=6, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='uniformresourcelocator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
