# Generated by Django 4.0.5 on 2022-07-06 15:33

from django.db import migrations, models
import django.db.models.deletion
import ipaddress


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_uniformresourcelocator_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL_Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(default=ipaddress.ip_address)),
                ('clicks_count', models.PositiveBigIntegerField(default=0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.uniformresourcelocator')),
            ],
        ),
    ]
