# Generated by Django 4.0.5 on 2022-07-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_url_click'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL_Click',
            new_name='UniformResourceLocatorClick',
        ),
    ]
