# Generated by Django 4.0.5 on 2022-07-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_rename_url_click_uniformresourcelocatorclick'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniformResourceLocatorClick',
            new_name='RedirectClickCount',
        ),
    ]
